# Generated by Django 4.2.6 on 2023-10-09 07:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/post_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Kordinators',
            fields=[
                ('name', models.CharField(max_length=25, verbose_name='Ismi')),
                ('lastname', models.CharField(max_length=25, verbose_name='Familiyasi')),
                ('surname', models.CharField(max_length=25, verbose_name='Otasining ismi')),
                ('age', models.IntegerField(verbose_name='Yoshi')),
                ('fak', models.CharField(choices=[('Metematika', 'Matematika'), ('Fizika', 'Fizika'), ("Sana'tshunoslik", "Sana'tshunoslik"), ('Jismoniy madaniyat', 'Jismoniy madaniyat'), ('Tabiy fanlar', 'Tabiy fanlar'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Rus tili va Qozoq tillari filialogiyasi', 'Rus tili va Qozoq tillari filialogiyasi'), ('Tibbiyot', 'Tibbiyot'), ("Maktabgacha va boshlang'ich ta'lim", "Maktabgacha va boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ('O‘zbek tili va adabiyoti fakulteti', 'O‘zbek tili va adabiyoti fakulteti')], default=None, max_length=155, verbose_name='Fakulteti')),
                ('ilimiy_darajasi', models.CharField(choices=[('Tugallanmangan bakalavr', 'Tugallanmangan bakalavr'), ('Magister', 'Magister')], max_length=25, verbose_name="Ma'lumoti")),
                ('kor_lavozimi', models.CharField(choices=[('Metematika', 'Matematika'), ('Fizika', 'Fizika'), ("Sana'tshunoslik", "Sana'tshunoslik"), ('Jismoniy madaniyat', 'Jismoniy madaniyat'), ('Tabiy fanlar', 'Tabiy fanlar'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Rus tili va Qozoq tillari filialogiyasi', 'Rus tili va Qozoq tillari filialogiyasi'), ('Tibbiyot', 'Tibbiyot'), ("Maktabgacha va boshlang'ich ta'lim", "Maktabgacha va boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ('O‘zbek tili va adabiyoti fakulteti', 'O‘zbek tili va adabiyoti fakulteti'), ('Tadbirkorlik va innovatsion loyihalar koordinatori', 'Tadbirkorlik va innovatsion loyihalar koordinatori'), ('Intellektual loyihalar koordinatori', 'Intellektual loyihalar koordinatori'), ('Besh tashabbus loyihalar koordinatori', 'Besh tashabbus loyihalar koordinatori'), ('Harbiy-vatanparvarlik loyihalar koordinatori', 'Harbiy-vatanparvarlik loyihalar koordinatori'), ('Yoshlar daftari va metsenatlik dasturlari koordinatori', 'Yoshlar daftari va metsenatlik dasturlari koordinatori'), ('Talaba qizlar koordinatori', 'Talaba qizlar koordinatori'), ('Matbuot kotibi, media guruh rahbari', 'Matbuot kotibi, media guruh rahbari')], max_length=255, verbose_name='Kordinatorligi')),
                ('tel', models.IntegerField(verbose_name='Telefon raqami')),
                ('image', models.ImageField(upload_to='media/Kordinator_logo/')),
                ('about', models.TextField(verbose_name="O'zi haqida")),
                ('telegram', models.CharField(max_length=250, verbose_name='Telegram link')),
                ('mail', models.CharField(max_length=250, verbose_name='Mail')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255, verbose_name='Post sarlavhasi')),
                ('post_content', models.TextField(verbose_name='Post content')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kordinators', verbose_name='Post kordinatori')),
                ('photos', models.ManyToManyField(blank=True, to='core.image')),
            ],
        ),
    ]
