# Generated by Django 4.2.6 on 2023-10-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kordinators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25, verbose_name='Ismi')),
                ('lastname', models.TextField(max_length=25, verbose_name='Familiyasi')),
                ('surname', models.TextField(max_length=25, verbose_name='Otasining ismi')),
                ('age', models.IntegerField(verbose_name='Yoshi')),
                ('fak', models.CharField(choices=[('Metematika', 'Matematika'), ('Fizika', 'Fizika')], default=None, max_length=155)),
            ],
        ),
    ]
