# Generated by Django 4.2.6 on 2023-10-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(choices=[('Matbuot kotibi', 'Matbuot kotibi'), ('Admin', 'Admin')], default=1, max_length=255, verbose_name='Author'),
            preserve_default=False,
        ),
    ]
