# Generated by Django 4.2.6 on 2023-10-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kordinators',
            name='fak',
            field=models.CharField(choices=[('Metematika', 'Matematika'), ('Fizika', 'Fizika')], default=None, max_length=155, verbose_name='Fakulteti'),
        ),
        migrations.AlterField(
            model_name='kordinators',
            name='lastname',
            field=models.CharField(max_length=25, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='kordinators',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='kordinators',
            name='surname',
            field=models.CharField(max_length=25, verbose_name='Otasining ismi'),
        ),
    ]
