# Generated by Django 4.2.6 on 2023-10-14 17:54

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_posts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/post_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='kordinators',
            name='image',
            field=models.ImageField(upload_to='media/Kordinator_logo/', validators=[core.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='photos',
            field=models.ManyToManyField(blank=True, to='core.image', validators=[core.models.validate_image_size], verbose_name='Post Images'),
        ),
    ]
