# Generated by Django 4.2.6 on 2023-10-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_image_image_alter_kordinators_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.image', verbose_name='Post Image'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='post_photos', to='core.image', verbose_name='Post Images'),
        ),
    ]
