# Generated by Django 4.2.6 on 2023-10-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_posts_image_alter_posts_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='photos',
        ),
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.image', verbose_name='Post Images'),
        ),
    ]
