# Generated by Django 4.2.6 on 2024-02-15 15:36

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kordinators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Ismi')),
                ('lastname', models.CharField(max_length=25, verbose_name='Familiyasi')),
                ('surname', models.CharField(max_length=25, verbose_name='Otasining ismi')),
                ('age', models.IntegerField(verbose_name='Yoshi')),
                ('fak', models.CharField(choices=[('Metematika - Informatika', 'Matematika - Informatika'), ('Fizika', 'Fizika'), ("Sana'tshunoslik", "Sana'tshunoslik"), ('Jismoniy madaniyat', 'Jismoniy madaniyat'), ('Tabiy fanlar', 'Tabiy fanlar'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Rus tili va Qozoq tillari filialogiyasi', 'Rus tili va Qozoq tillari filialogiyasi'), ('Tibbiyot', 'Tibbiyot'), ("Maktabgacha va boshlang'ich ta'lim", "Maktabgacha va boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ('O‘zbek tili va adabiyoti fakulteti', 'O‘zbek tili va adabiyoti fakulteti')], default=None, max_length=155, verbose_name='Fakulteti')),
                ('ilimiy_darajasi', models.CharField(choices=[('Tugallanmangan oliy', 'Tugallanmangan oliy'), ('Magistr', 'Magistr')], max_length=25, verbose_name="Ma'lumoti")),
                ('kor_lavozimi', models.CharField(choices=[('Metematika - Informatika', 'Matematika - Informatika '), ('Fizika', 'Fizika'), ("Sana'tshunoslik", "Sana'tshunoslik"), ('Jismoniy madaniyat', 'Jismoniy madaniyat'), ('Tabiy fanlar', 'Tabiy fanlar'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Rus tili va Qozoq tillari filialogiyasi', 'Rus tili va Qozoq tillari filialogiyasi'), ('Tibbiyot', 'Tibbiyot'), ("Maktabgacha va boshlang'ich ta'lim", "Maktabgacha va boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ('O‘zbek tili va adabiyoti fakulteti', 'O‘zbek tili va adabiyoti fakulteti'), ('Tadbirkorlik va innovatsion loyihalar koordinatori', 'Tadbirkorlik va innovatsion loyihalar koordinatori'), ('Intellektual loyihalar koordinatori', 'Intellektual loyihalar koordinatori'), ('Besh tashabbus loyihalar koordinatori', 'Besh tashabbus loyihalar koordinatori'), ('Harbiy-vatanparvarlik loyihalar koordinatori', 'Harbiy-vatanparvarlik loyihalar koordinatori'), ('Yoshlar daftari va metsenatlik dasturlari koordinatori', 'Yoshlar daftari va metsenatlik dasturlari koordinatori'), ('Talaba qizlar koordinatori', 'Talaba qizlar koordinatori'), ('Matbuot kotibi, media guruh rahbari', 'Matbuot kotibi, media guruh rahbari')], max_length=255, verbose_name='Kordinatorligi')),
                ('tel', models.IntegerField(verbose_name='Telefon raqami')),
                ('image', models.ImageField(upload_to='Kordinator_logo/', validators=[app.models.validate_image_size])),
                ('about', models.TextField(verbose_name="O'zi haqida")),
                ('telegram', models.CharField(max_length=250, verbose_name='Telegram link')),
                ('mail', models.CharField(max_length=250, verbose_name='Mail')),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qalqon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fakultet', models.CharField(choices=[('Metematika - Informatika', 'Matematika - Informatika'), ('Fizika', 'Fizika'), ("Sana'tshunoslik", "Sana'tshunoslik"), ('Jismoniy madaniyat', 'Jismoniy madaniyat'), ('Tabiy fanlar', 'Tabiy fanlar'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Rus tili va Qozoq tillari filialogiyasi', 'Rus tili va Qozoq tillari filialogiyasi'), ('Tibbiyot', 'Tibbiyot'), ("Maktabgacha va boshlang'ich ta'lim", "Maktabgacha va boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ('O‘zbek tili va adabiyoti fakulteti', 'O‘zbek tili va adabiyoti fakulteti')], max_length=255, verbose_name='Fakultetni tanlang')),
                ('yigit_jamoa_soni', models.IntegerField(verbose_name='Yigit bolalar soni')),
                ('qiz_jamoa_soni', models.IntegerField(verbose_name='Qiz bolalar soni')),
                ('all_stat_file', models.FileField(blank=True, null=True, upload_to='qalqon/', verbose_name="Faylni briktiring mavjud bo'lsa")),
            ],
            options={
                'verbose_name': 'Qalqon',
                'verbose_name_plural': "Qalqon jamoasining ro'yxati",
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_name', models.CharField(max_length=255, verbose_name='Topshiriq nomi')),
                ('task_body', models.TextField(verbose_name='Topshiriq Mazmuni')),
                ('task_date', models.DateTimeField(verbose_name='Topshiriq yuklangan vaqt')),
                ('task_and_date', models.DateTimeField(verbose_name='Topshiriq tugash vaqti')),
                ('task_file', models.FileField(blank=True, null=True, upload_to='topshiriqlar/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False, null=True, verbose_name='vazifalalrning qabul qilinish holati')),
                ('coordinators', models.ManyToManyField(blank=True, to='app.kordinators', verbose_name='Koordinatorlani tanlash')),
            ],
        ),
        migrations.CreateModel(
            name='Tavsiyanoma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fakultet', models.CharField(choices=[('Metematika - Informatika', 'Matematika - Informatika'), ('Fizika', 'Fizika'), ("Sana'tshunoslik", "Sana'tshunoslik"), ('Jismoniy madaniyat', 'Jismoniy madaniyat'), ('Tabiy fanlar', 'Tabiy fanlar'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Rus tili va Qozoq tillari filialogiyasi', 'Rus tili va Qozoq tillari filialogiyasi'), ('Tibbiyot', 'Tibbiyot'), ("Maktabgacha va boshlang'ich ta'lim", "Maktabgacha va boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ('O‘zbek tili va adabiyoti fakulteti', 'O‘zbek tili va adabiyoti fakulteti')], max_length=255, verbose_name='Fakultetni tanlang')),
                ('yigit_jamoa_soni', models.IntegerField(verbose_name='Yigit bolalar soni')),
                ('qiz_jamoa_soni', models.IntegerField(verbose_name='Qiz bolalar soni')),
                ('all_stat_file', models.FileField(blank=True, null=True, upload_to='tavsiyanoma/', verbose_name="Faylni briktiring mavjud bo'lsa")),
            ],
            options={
                'verbose_name': 'Tavsiya noma',
                'verbose_name_plural': "Tavsiya noma asosida ta'lim oluvchilar",
            },
        ),
        migrations.CreateModel(
            name='Utizbeshfoiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fakultet', models.CharField(choices=[('Metematika - Informatika', 'Matematika - Informatika'), ('Fizika', 'Fizika'), ("Sana'tshunoslik", "Sana'tshunoslik"), ('Jismoniy madaniyat', 'Jismoniy madaniyat'), ('Tabiy fanlar', 'Tabiy fanlar'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Rus tili va Qozoq tillari filialogiyasi', 'Rus tili va Qozoq tillari filialogiyasi'), ('Tibbiyot', 'Tibbiyot'), ("Maktabgacha va boshlang'ich ta'lim", "Maktabgacha va boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ('O‘zbek tili va adabiyoti fakulteti', 'O‘zbek tili va adabiyoti fakulteti')], max_length=255, verbose_name='Fakultetni tanlang')),
                ('yigit_jamoa_soni', models.IntegerField(verbose_name='Yigit bolalar soni')),
                ('qiz_jamoa_soni', models.IntegerField(verbose_name='Qiz bolalar soni')),
                ('all_stat_file', models.FileField(blank=True, null=True, upload_to='uttizbesh/', verbose_name="Faylni briktiring mavjud bo'lsa")),
            ],
            options={
                'verbose_name': '35% lik',
                'verbose_name_plural': "35% lik kontrakt asosida ta'lim oluvchilar",
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completed_file', models.FileField(blank=True, null=True, upload_to='completed_tasks/')),
                ('is_late_submission', models.BooleanField(default=False, verbose_name='Vazifa kechikib yuborilgan')),
                ('completed', models.BooleanField(default=False, verbose_name='Vazifa yakunlangan')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kordinators')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
            ],
        ),
        migrations.CreateModel(
            name='AddWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('desc', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('file', models.FileField(blank=True, null=True, upload_to='work/')),
                ('accepted', models.BooleanField(default=False, verbose_name='Tasdiq xolati  ❌/✅ ')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
            ],
        ),
    ]
