# Generated by Django 4.2.6 on 2024-02-15 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kordinators',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='kordinators',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
