# Generated by Django 4.2.6 on 2024-02-11 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addwork',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='addwork',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='addwork',
            name='date',
        ),
        migrations.AddField(
            model_name='addwork',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addwork',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='completed_tasks/'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='completion_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kordinators'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='is_late_submission',
            field=models.BooleanField(default=False, verbose_name='Vazifa kechikib yuborilgan'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
