# Generated by Django 4.2.6 on 2023-10-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='received_by',
            field=models.ManyToManyField(blank=True, related_name='received_tasks', to='app.kordinators', verbose_name='Received by Coordinators'),
        ),
    ]
