# Generated by Django 4.2.9 on 2024-02-20 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_kordinators_is_available_alter_kordinators_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTashabbus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tashabbus', models.CharField(max_length=255, verbose_name='Tashabbus nomi')),
            ],
            options={
                'verbose_name': 'Tashabbus nomi',
                'verbose_name_plural': 'Tashabbuslar nomi',
            },
        ),
        migrations.CreateModel(
            name='AddTashabbusCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tashabbus_category', models.CharField(max_length=255, verbose_name='TAshabbus kategoriyasi')),
                ('tashabbus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addtashabbus', verbose_name='Tashabbus nomi')),
            ],
            options={
                'verbose_name': 'Tashabbus nomi',
                'verbose_name_plural': "Tashabbus yo'nalishlari",
            },
        ),
        migrations.AlterModelOptions(
            name='addwork',
            options={'verbose_name': 'Shaxsiy qilingan ishlar', 'verbose_name_plural': 'Shaxsiy qilingan ishlar'},
        ),
        migrations.AlterModelOptions(
            name='kordinators',
            options={'verbose_name': 'Koordinatorlar', 'verbose_name_plural': "Koordinatorlar ro'yxati"},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Topshiriqlar ', 'verbose_name_plural': 'Topshiriqlar umumiy'},
        ),
        migrations.AlterModelOptions(
            name='taskcompletion',
            options={'verbose_name': 'Topshiriqlar ijrosi', 'verbose_name_plural': 'Topshiriqlarning ijrosi'},
        ),
        migrations.AlterField(
            model_name='addwork',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addwork',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addwork',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addwork',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kordinators',
            name='ilimiy_darajasi',
            field=models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr')], max_length=25, verbose_name="Ma'lumoti"),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Topshiriqlar xolati ❌/✅'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='completed_tasks/', verbose_name='Biriktirilgan fayl'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='completion_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Topshirilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='description',
            field=models.TextField(verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='is_late_submission',
            field=models.BooleanField(default=False, verbose_name="Topshiriqlar kechikib yuborilgan yo'q ❌/✅ ha "),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task', verbose_name='Topshiriqlar'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Sarlahasi'),
        ),
        migrations.CreateModel(
            name='TashabbusTadbir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tadbir sarlavhasi')),
                ('content', models.TextField(max_length=255, verbose_name='Tadbir mazmuni')),
                ('file', models.FileField(blank=True, null=True, upload_to='tashabbus/', verbose_name="Faylni briktiring mavjud bo'lsa")),
                ('tashabbus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addtashabbus', verbose_name='Tashabbus nomi')),
                ('tashabbus_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addtashabbuscategory', verbose_name='TAshabbus kategoriyasi')),
            ],
            options={
                'verbose_name': 'Tashabbus tadbir',
                'verbose_name_plural': 'Tashabbus tadbirlari',
            },
        ),
    ]
