# Generated by Django 4.2.6 on 2024-02-11 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_addwork_completed_remove_addwork_coordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addwork',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Tasdiq xolati  ❌/✅ '),
        ),
        migrations.AlterField(
            model_name='addwork',
            name='desc',
            field=models.TextField(verbose_name="Qisqacha ma'lumot"),
        ),
        migrations.AlterField(
            model_name='addwork',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi'),
        ),
        migrations.AlterField(
            model_name='addwork',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
    ]
