# Generated by Django 4.2.9 on 2024-02-20 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addtashabbus_addtashabbuscategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddIntelektual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intelektual', models.CharField(choices=[('Talabalar ligasi', 'Talabalar ligasi'), ('Intellektual liga', 'Intellektual liga'), ('Rektor kubogi', 'Rektor kubogi'), ('Breyn Ring', 'Breyn Ring'), ('Zakovat Quiz', 'Zakovat Quiz'), ("Shaxsiy o'yin", "Shaxsiy o'yin")], max_length=255, verbose_name='Intelektual loyiha nomi')),
                ('title', models.CharField(max_length=255, verbose_name='Tadbir sarlavhasi')),
                ('content', models.TextField(max_length=255, verbose_name='Tadbir mazmuni')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('file', models.FileField(blank=True, null=True, upload_to='tashabbus/', verbose_name="Faylni briktiring mavjud bo'lsa")),
            ],
            options={
                'verbose_name': 'Intelektual',
                'verbose_name_plural': 'Intelektual loyiha tadbirlari',
            },
        ),
    ]
