# Generated by Django 4.2.6 on 2023-10-29 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_notification_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completed_file', models.FileField(blank=True, null=True, upload_to='completed_tasks/')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kordinators')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
