# Generated by Django 4.2.6 on 2023-10-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_taskcompletion_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Task Completed'),
        ),
    ]
