# Generated by Django 4.2.6 on 2023-11-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_taskcompletion_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcompletion',
            name='completed',
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='is_late_submission',
            field=models.BooleanField(default=False, verbose_name='Is Late Submission'),
        ),
    ]
