# Generated by Django 4.2.6 on 2023-11-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_taskcompletion_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Task Completed'),
        ),
    ]
