# Generated by Django 4.2.6 on 2023-11-08 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_taskcompletion_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='work/')),
                ('accepted', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
