# Generated by Django 4.2.7 on 2023-11-09 13:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_addwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kordinators',
            name='image',
            field=models.ImageField(upload_to='Kordinator_logo/', validators=[app.models.validate_image_size]),
        ),
    ]
