# Generated by Django 4.2.7 on 2023-11-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_kordinators_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=255, verbose_name='Topshiriq nomi'),
        ),
    ]
