# Generated by Django 4.2.6 on 2023-12-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_kordinators_fak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='received_by',
        ),
    ]
