# Generated by Django 4.2.6 on 2023-12-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_task_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, null=True, verbose_name='Task Completed'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Vazifa yakunlangan'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='is_late_submission',
            field=models.BooleanField(default=False, verbose_name='Vazifa kechikib yuborilgan'),
        ),
    ]
