# Generated by Django 4.2.6 on 2023-12-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_task_completed_alter_taskcompletion_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, null=True, verbose_name='vazifalalrning qabul qilinish holati'),
        ),
        migrations.AlterField(
            model_name='task',
            name='coordinators',
            field=models.ManyToManyField(blank=True, to='app.kordinators', verbose_name='Koordinatorlani tanlash'),
        ),
    ]
