# Generated by Django 4.2.6 on 2024-01-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_task_completed_alter_task_coordinators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qalqon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakultet', models.CharField(choices=[('Metematika - Informatika', 'Matematika - Informatika'), ('Fizika', 'Fizika'), ("Sana'tshunoslik", "Sana'tshunoslik"), ('Jismoniy madaniyat', 'Jismoniy madaniyat'), ('Tabiy fanlar', 'Tabiy fanlar'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Rus tili va Qozoq tillari filialogiyasi', 'Rus tili va Qozoq tillari filialogiyasi'), ('Tibbiyot', 'Tibbiyot'), ("Maktabgacha va boshlang'ich ta'lim", "Maktabgacha va boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ('O‘zbek tili va adabiyoti fakulteti', 'O‘zbek tili va adabiyoti fakulteti')], max_length=255, verbose_name='Fakultetni tanlang')),
                ('yigit_jamoa_soni', models.IntegerField(verbose_name='Yigit bolalar soni')),
                ('qiz_jamoa_soni', models.IntegerField(verbose_name='Qiz bolalar soni')),
                ('all_stat_file', models.FileField(blank=True, null=True, upload_to='beshtashabbus/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kordinators')),
            ],
            options={
                'verbose_name': 'Qalqon',
                'verbose_name_plural': "Qalqon jamoasining ro'yxati",
            },
        ),
    ]
