# Generated by Django 4.2.6 on 2024-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_qalqon_all_stat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='qalqon',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
