# Generated by Django 4.2.6 on 2024-01-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_qalqon_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qalqon',
            name='history',
        ),
    ]
