# Generated by Django 4.2.6 on 2024-01-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_tavsiyanoma_alter_qalqon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qalqon',
            name='all_stat_file',
            field=models.FileField(blank=True, null=True, upload_to='qalqon/', verbose_name="Faylni briktiring mavjud bo'lsa"),
        ),
        migrations.AlterField(
            model_name='tavsiyanoma',
            name='all_stat_file',
            field=models.FileField(blank=True, null=True, upload_to='tavsiyanoma/', verbose_name="Faylni briktiring mavjud bo'lsa"),
        ),
    ]
