# Generated by Django 4.2.6 on 2024-01-04 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_qalqon_all_stat_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utizbeshfoiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fakultet', models.CharField(choices=[('Metematika - Informatika', 'Matematika - Informatika'), ('Fizika', 'Fizika'), ("Sana'tshunoslik", "Sana'tshunoslik"), ('Jismoniy madaniyat', 'Jismoniy madaniyat'), ('Tabiy fanlar', 'Tabiy fanlar'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Rus tili va Qozoq tillari filialogiyasi', 'Rus tili va Qozoq tillari filialogiyasi'), ('Tibbiyot', 'Tibbiyot'), ("Maktabgacha va boshlang'ich ta'lim", "Maktabgacha va boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ('O‘zbek tili va adabiyoti fakulteti', 'O‘zbek tili va adabiyoti fakulteti')], max_length=255, verbose_name='Fakultetni tanlang')),
                ('yigit_jamoa_soni', models.IntegerField(verbose_name='Yigit bolalar soni')),
                ('qiz_jamoa_soni', models.IntegerField(verbose_name='Qiz bolalar soni')),
                ('all_stat_file', models.FileField(blank=True, null=True, upload_to='uttizbesh/', verbose_name="Faylni briktiring mavjud bo'lsa")),
            ],
            options={
                'verbose_name': '35% lik',
                'verbose_name_plural': "35% lik kontrakt asosida ta'lim oluvchilar",
            },
        ),
        migrations.AlterModelOptions(
            name='tavsiyanoma',
            options={'verbose_name': 'Tavsiya noma', 'verbose_name_plural': "Tavsiya noma asosida ta'lim oluvchilar"},
        ),
    ]
