# Generated by Django 4.2.6 on 2024-01-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_utizbeshfoiz_alter_tavsiyanoma_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakovaComand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Jamoa nomi')),
                ('count', models.IntegerField(max_length=255, verbose_name="A'zolar soni")),
                ('fakultets', models.CharField(choices=[('Metematika - Informatika', 'Matematika - Informatika'), ('Fizika', 'Fizika'), ("Sana'tshunoslik", "Sana'tshunoslik"), ('Jismoniy madaniyat', 'Jismoniy madaniyat'), ('Tabiy fanlar', 'Tabiy fanlar'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Rus tili va Qozoq tillari filialogiyasi', 'Rus tili va Qozoq tillari filialogiyasi'), ('Tibbiyot', 'Tibbiyot'), ("Maktabgacha va boshlang'ich ta'lim", "Maktabgacha va boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ('O‘zbek tili va adabiyoti fakulteti', 'O‘zbek tili va adabiyoti fakulteti')], max_length=255, verbose_name='Fakultetni tanlang')),
            ],
            options={
                'verbose_name': 'Zakovat komand',
                'verbose_name_plural': 'Zakovat jamoalari',
            },
        ),
    ]
