# Generated by Django 4.2.6 on 2024-01-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_zakovacomand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakovacomand',
            options={},
        ),
    ]
