# Generated by Django 4.2.6 on 2024-01-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_zakovacomand_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZakovaComand',
        ),
    ]
